name: ATS FullStack Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configure AWS credentials for Terraform
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Install Terraform CLI
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.7.5"

    # Terraform Init
    - name: Terraform Init
      working-directory: infra
      run: terraform init

    # Terraform Validate
    - name: Terraform Validate
      working-directory: infra
      run: terraform validate

    # Terraform Apply
    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve

    # Install jq (optional but safe to have)
    - name: Install jq
      run: sudo apt-get install -y jq

    # Prepare SSH Private Key for Ansible
    - name: Prepare SSH Private Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/privkey
        chmod 600 /tmp/privkey

    # Install Ansible
    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible

    # Install Node.js (required for frontend build)
    - name: Install NodeJS
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt install -y nodejs

    # Run Ansible playbook using Terraform output directly as inventory
    - name: Deploy Using Ansible
      env:
       DB_NAME: ${{ secrets.DB_NAME }}
       DB_USER: ${{ secrets.DB_USER }}
       DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
       IP=$(terraform -chdir=infra output -raw public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
       ansible-playbook -i "$IP," ansible/playbook.yml --private-key /tmp/privkey -u ubuntu

